-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE public.contribution_bookmarks (
--   user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
--   contribution_id uuid NOT NULL REFERENCES public.contributions(id) ON DELETE CASCADE,
--   created_at timestamptz NOT NULL DEFAULT now(),
--   PRIMARY KEY (user_id, contribution_id)
-- );
